In [13]:
import pandas as pd
import numpy as np
from pathlib import Path
import re

In [14]:
df = pd.read_csv("../data/processed/cases.csv")

print(df.shape)
df.head()

(31, 6)

,case_id,nomor_perkara,jenis_perkara,ringkasan_fakta,panjang_teks,text_full
0,case_001,052/phpu.c.1-ii/2004 demi keadilan berdasarkan...,Pertanahan,p u t u s a n perkara nomor: 052/phpu.c.1-ii/2...,1000,p u t u s a n perkara nomor: 052/phpu.c.1-ii/2...
1,case_002,95/puu-xii/2014 demi keadilan berdasarkan ketu...,Pertanahan,salinan putusan nomor 95/puu-xii/2014 demi kea...,60565,salinan putusan nomor 95/puu-xii/2014 demi kea...
2,case_003,96/puu-xiv/2016 demi keadilan berdasarkan ketu...,Pertanahan,salinan putusan nomor 96/puu-xiv/2016 demi kea...,91722,salinan putusan nomor 96/puu-xiv/2016 demi kea...
3,case_004,113-10-18/phpu.dpr-dprd/xvii/2019 demi keadila...,Pertanahan,sal inan ketetapan nomor 113-10-18/phpu.dpr-dp...,912,sal inan ketetapan nomor 113-10-18/phpu.dpr-dp...
4,case_005,99/puu-xx/2022 demi keadilan berdasarkan ketuh...,Pertanahan,1 s ali n an ketetapan nomor 99/puu-xx/2022 de...,869,1 s ali n an ketetapan nomor 99/puu-xx/2022 de...

In [15]:
print(df.columns)

Index(['case_id', 'nomor_perkara', 'jenis_perkara', 'ringkasan_fakta',
       'panjang_teks', 'text_full'],
      dtype='object')

In [16]:
df["text_full"] = df["text_full"].fillna("")
df["nomor_perkara"] = df["nomor_perkara"].fillna("unknown")
df["jenis_perkara"] = df["jenis_perkara"].fillna("unknown")

In [17]:
df["panjang_teks"] = df["text_full"].apply(lambda x: len(str(x).split()))

In [18]:
def simple_summary(text, max_words=80):
    words = str(text).split()
    return " ".join(words[:max_words])

df["ringkasan_fakta"] = df["text_full"].apply(simple_summary)

In [19]:
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df["text_clean"] = df["text_full"].apply(clean_text)

In [20]:
df_final = df[[
    "case_id",
    "nomor_perkara",
    "jenis_perkara",
    "ringkasan_fakta",
    "panjang_teks",
    "text_full"
]]

df_final.head()

,case_id,nomor_perkara,jenis_perkara,ringkasan_fakta,panjang_teks,text_full
0,case_001,052/phpu.c.1-ii/2004 demi keadilan berdasarkan...,Pertanahan,p u t u s a n perkara nomor: 052/phpu.c.1-ii/2...,1000,p u t u s a n perkara nomor: 052/phpu.c.1-ii/2...
1,case_002,95/puu-xii/2014 demi keadilan berdasarkan ketu...,Pertanahan,salinan putusan nomor 95/puu-xii/2014 demi kea...,60565,salinan putusan nomor 95/puu-xii/2014 demi kea...
2,case_003,96/puu-xiv/2016 demi keadilan berdasarkan ketu...,Pertanahan,salinan putusan nomor 96/puu-xiv/2016 demi kea...,91722,salinan putusan nomor 96/puu-xiv/2016 demi kea...
3,case_004,113-10-18/phpu.dpr-dprd/xvii/2019 demi keadila...,Pertanahan,sal inan ketetapan nomor 113-10-18/phpu.dpr-dp...,912,sal inan ketetapan nomor 113-10-18/phpu.dpr-dp...
4,case_005,99/puu-xx/2022 demi keadilan berdasarkan ketuh...,Pertanahan,1 s ali n an ketetapan nomor 99/puu-xx/2022 de...,869,1 s ali n an ketetapan nomor 99/puu-xx/2022 de...

In [21]:
Path("../data/processed").mkdir(parents=True, exist_ok=True)

df_final.to_csv(
    "../data/processed/cases.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Dataset Case Representation tersimpan!")

Dataset Case Representation tersimpan!