In [70]:
import pandas as pd

df = pd.read_csv("../data/processed/cases.csv")

df.head()

,case_id,nomor_perkara,jenis_perkara,ringkasan_fakta,panjang_teks,text_full,amar_putusan
0,case_001,052/phpu.c.1-ii/2004 demi keadilan berdasarkan...,Pertanahan,p u t u s a n perkara nomor: 052/phpu.c.1-ii/2...,1000,p u t u s a n perkara nomor: 052/phpu.c.1-ii/2...,"mengadili, dan memutus perkara konstitusi pada..."
1,case_002,95/puu-xii/2014 demi keadilan berdasarkan ketu...,Pertanahan,salinan putusan nomor 95/puu-xii/2014 demi kea...,60565,salinan putusan nomor 95/puu-xii/2014 demi kea...,amar putusan mengadili; menyatakan
2,case_003,96/puu-xiv/2016 demi keadilan berdasarkan ketu...,Pertanahan,salinan putusan nomor 96/puu-xiv/2016 demi kea...,91722,salinan putusan nomor 96/puu-xiv/2016 demi kea...,amar putusan sebagai berikut: 1) menyatakan
3,case_004,113-10-18/phpu.dpr-dprd/xvii/2019 demi keadila...,Pertanahan,sal inan ketetapan nomor 113-10-18/phpu.dpr-dp...,912,sal inan ketetapan nomor 113-10-18/phpu.dpr-dp...,mengadili perkara konstitusi pada tingkat pert...
4,case_005,99/puu-xx/2022 demi keadilan berdasarkan ketuh...,Pertanahan,1 s ali n an ketetapan nomor 99/puu-xx/2022 de...,869,1 s ali n an ketetapan nomor 99/puu-xx/2022 de...,memutuskan mencabut permohonan a quo; d. bahwa...

In [71]:
df["text_full"].iloc[0][:1000]

'p u t u s a n perkara nomor: 052/phpu.c.1-ii/2004 demi keadilan berdasarkan ketuhanan yang maha esa mahkamah konstitusi republik indonesia yang memeriksa, mengadili, dan memutus perkara konstitusi pada tingkat pertama dan terakhir, telah menjatuhkan putusan dalam perkara perselisihan hasil pemilihan umum yang diajukan oleh: 1. nama tempat tanggal lahir/umur : prof.dr.m.ryaas rasyid. ma : gowa,17 desesember 1949 agama pekerjaan kewarganegaraan alamat : : : : islam dosen indonesia jl. bango raya no.6 pondok labu jakarta 2. nama tempat tanggal lahir/umur agama pekerjaan kewarganegaraan alamat islam : rivai pulungan,dipl ing : tarutung, 07 januari 1944 : : wiraswasta : indonesia : jl.kencana permai ic pondok pinang jakarta nomor telepon selatan - : dalam hal ini masing-masing sebagai ketua umum dan sekretaris jenderal, bertindak untuk dan atas nama partai demokrasi kebangsaan, peserta 1 pemilihan umum anggota dpr, dpd, dan dprd tahun 2004, selanjutnya disebut sebagai pemohon; telah membaca'

In [72]:
import re

def extract_amar(text):

    text = str(text).lower()

    patterns = [
        r"amar\s+putusan(.*?)(menyatakan|memutuskan|demikianlah)",
        r"memutuskan(.*?)(demikian|ditetapkan)",
        r"mengadili(.*?)(demikian|ditetapkan)"
    ]

    for pattern in patterns:

        match = re.search(pattern, text, re.DOTALL)

        if match:
            return match.group(0)[:2000]

    return "AMAR TIDAK DITEMUKAN"

In [73]:
df["amar_putusan"] = df["text_full"].apply(extract_amar)

df[["case_id", "amar_putusan"]].head()

    case_id                                       amar_putusan
0  case_001  mengadili, dan memutus perkara konstitusi pada...
1  case_002                 amar putusan mengadili; menyatakan
2  case_003        amar putusan sebagai berikut: 1) menyatakan
3  case_004  mengadili perkara konstitusi pada tingkat pert...
4  case_005  memutuskan mencabut permohonan a quo; d. bahwa...

In [74]:
df["amar_putusan"].value_counts().head()

amar_putusan
amar putusan mengadili, menyatakan                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  7
amar putusan mengadili: menyatakan                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  2
amar putusan mahkamah sebagaimana dimaksud pada ayat (1) menyatakan                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 2
mengadili perkara konstitusi pada tingkat pertama dan terakhir, menjatuhkan ketetapan dalam perkara perselisihan hasil pemilihan umum anggota dewan perwakilan rakyat dan dewan perwakilan rakyat daerah tahun 2019 menjatuhkan ketetapan sebagai berikut: menimbang : a. bahwa mahkamah konstitusi telah menerima permohonan bertanggal 23 mei 2019, yang diajukan oleh sopyan hakim, s.kep.ners., calon anggota dprd kabupaten daerah pemilihan lombok timur 2 dari partai persatuan pembangunan nomor urut 10, berdasarkan surat kuasa khusus nomor 083/sk.pdn/adv.is/is.p/v/2019 bertanggal 21 mei 2019 memberi kuasa kepada iskandar, s.h., m.h., lalu rusdi, s.h., gufran, s.h., semuanya adalah advokat/auditor hukum/konsultan hukum yang beralamat pada kantor advokat & auditor hukum iskandar & partners, di gedung graha dekopinwil nusa tenggara barat lantai 2, jalan bung karno nomor 30 mataram, provinsi nusa tenggara barat, yang diterima kepaniteraan mahkamah konstitusi pada tanggal 23 mei 2019 sesuai akta pengajuan permohonan pemohon nomor 53-10-18/ap3-dpr- dprd/pan.mk/2019 bertanggal 23 mei 2019 dan dicatat dalam buku registrasi perkara konstitusi dengan nomor 113-10-18/phpu.dpr-dprd/xvii/2019 pada tanggal 1 juli 2019 mengenai permohonan perselisihan hasil pemilihan 2 umum anggota dewan perwakilan rakyat dan dewan perwakilan rakyat daerah tahun 2019; b. bahwa terhadap permohonan nomor 113-10-18/phpu.dpr- dprd/xvii/2019 tersebut mahkamah konstitusi telah menerbitkan: 1. ketetapan ketua mahkamah konstitusi nomor 183/dpr- dprd/tap.mk/07/2019 tentang pembentukan panel hakim untuk memeriksa perkara nomor 113-10- 18/phpu.dpr-dprd/xvii/2019, bertanggal 01 juli 2019; 2. ketetapan ketua panel mahkamah konstitusi nomor 242/dpr-dprd/tap-hs/mk/07/2019 tentang penetapan hari sidang pertama untuk memeriksa perkara nomor 113-10-18/phpu.dpr-dprd/xvii/2019, bertanggal 01 juli 2019; c. bahwa mahkamah telah mengagendakan pemeriksaan pendahuluan terhadap permohonan tersebut melalui sidang panel pada tanggal 12    1
mengadili, dan memutus perkara konstitusi pada tingkat pertama dan terakhir, telah menjatuhkan putusan dalam perkara perselisihan hasil pemilihan umum yang diajukan oleh: 1. nama tempat tanggal lahir/umur : prof.dr.m.ryaas rasyid. ma : gowa,17 desesember 1949 agama pekerjaan kewarganegaraan alamat : : : : islam dosen indonesia jl. bango raya no.6 pondok labu jakarta 2. nama tempat tanggal lahir/umur agama pekerjaan kewarganegaraan alamat islam : rivai pulungan,dipl ing : tarutung, 07 januari 1944 : : wiraswasta : indonesia : jl.kencana permai ic pondok pinang jakarta nomor telepon selatan - : dalam hal ini masing-masing sebagai ketua umum dan sekretaris jenderal, bertindak untuk dan atas nama partai demokrasi kebangsaan, peserta 1 pemilihan umum anggota dpr, dpd, dan dprd tahun 2004, selanjutnya disebut sebagai pemohon; telah membaca permohonan pemohon; telah mendengar keterangan pemohon; telah mendengar keterangan komisi pemilihan umum; telah membaca keterangan tertulis komisi pemilihan umum; telah memeriksa bukti-bukti; duduk perkara menimbang bahwa pemohon telah mengajukan permohonan dengan surat permohonannya: bertanggal 7 mei 2004 melalui faksimili diterima di kepaniteraan mahkamah konstitusi republik indonesia pada hari sabtu, tanggal 8 mei 2004 pukul 14.09 wib dan diregistrasi pada hari selasa, tanggal 11 mei 2004 pukul 18.00 wib, dengan nomor 052/phpu.c1-ii/2004 yang pada pokoknya pemohon mengemukakan dalil-dalil sebagai berikut: pemohon adalah presiden partai dan sekretaris jenderal partai persatuan demokrasi kebangsaan, peserta pemilihan umum anggota dpr, dpd, dan dprd tahun 2004 yang terdaftar di komisi pemilhan umum (kpu). pemohon berkeberatan terhadap penetapan komisi pemilihan umum (kpu) nomor. 44/sk/kpu/thn 2004, tanggal 05 mei 2004, tentang hasil perhitungan suara pemilihan umum anggota dpr,dpd dan dprd tahun 2004- 2009 secara nasional untuk daerah pemilihan kabupaten kerom 1(satu) provinsi papua yang hasil perhitungan sebagai berikut : 1. jumlah per    1
Name: count, dtype: int64

In [75]:
df.to_csv(
    "../data/processed/cases.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Dataset dengan amar_putusan tersimpan")

Dataset dengan amar_putusan tersimpan

In [76]:
case_solutions = {}

for _, row in df.iterrows():
    case_solutions[row["case_id"]] = row["amar_putusan"]

print("Total cases:", len(case_solutions))

Total cases: 31

In [77]:
print("retrieve" in globals())

True

In [78]:
def get_top_solutions(query, k=5):

    top_cases = retrieve(query, k=k)

    solutions = []

    for cid in top_cases["case_id"]:
        solutions.append(case_solutions[cid])

    return solutions

In [79]:
query = "pengujian undang undang kehutanan"

get_top_solutions(query)

['amar putusan pengadilan tindak pidana korupsi pada pengadilan negeri medan no. 42/pid.sus-tpk/2021/pn. mdn: 1. menyatakan',
 'amar putusan mengadili, menyatakan',
 'mengadili perkara konstitusi pada tingkat pertama dan terakhir, menjatuhkan ketetapan dalam perkara pengujian formil peraturan pemerintah pengganti undang-undang nomor 2 tahun 2022 tentang cipta kerja terhadap undang-undang dasar negara republik indonesia tahun 1945, sebagai berikut: menimbang : a. bahwa mahkamah konstitusi telah menerima permohonan yang diajukan oleh konfederasi serikat buruh seluruh indonesia (ksbsi) dalam hal ini diwakili oleh elly rosita silaban selaku presiden dewan eksekutif nasional ksbsi, dan dedi hardianto selaku sekretaris jenderal dewan eksekutif nasional ksbsi yang diterima kepaniteraan mahkamah konstitusi pada tanggal 9 januari 2023 berdasarkan akta pengajuan permohonan pemohon nomor 3/puu/pan.mk/ap3/01/2023, bertanggal 10 januari 2023 dan telah dicatat dalam buku registrasi perkara konstitusi elektronik (e-brpk) pada tanggal 11 januari 2023 dengan nomor 6/puu-xxi/2023 mengenai pengujian formil peraturan pemerintah pengganti undang-undang nomor 2 tahun 2022 tentang cipta kerja terhadap undang-undang dasar negara republik indonesia tahun 1945; b. bahwa sesuai dengan ketentuan pasal 28 ayat (4) dan pasal 34 ayat (1) undang-undang nomor 24 tahun 2003 tentang mahkamah konstitusi sebagaimana telah diubah terakhir dengan undang-undang nomor 7 tahun 2020 tentang perubahan ketiga atas undang-undang nomor 24 tahun 2003 tentang mahkamah konstitusi (lembaran negara republik indonesia tahun 2020 nomor 216, tambahan lembaran negara republik indonesia nomor 6554, 2 selanjutnya disebut uu mk), terhadap permohonan nomor 6/puu-xxi/2023 tersebut mahkamah konstitusi telah menerbitkan: 1) ketetapan ketua mahkamah konstitusi nomor 6.6/ puu/tap.mk/panel/01/2023 tentang pembentukan panel hakim untuk memeriksa perkara nomor 6/puu-xxi/2023, bertanggal 13 januari 2023; 2) ketetapan ketua panel hakim mahkamah konstitusi nomor 6.6/puu/tap.mk/hs/1/2023 tentang penetapan hari sidang pertama untuk memeriksa perkara nomor 6/puu-xxi/2023, bertanggal 11 januari 2023; c.',
 'amar putusan mengadili: menyatakan',
 'amar putusan mengadili, menyatakan']

In [80]:
def predict_majority(query, k=5):

    solutions = get_top_solutions(query, k)

    vote = Counter(solutions)

    return vote.most_common(1)[0][0]

In [81]:
predict_majority(
    "pengujian undang undang kehutanan"
)

'amar putusan mengadili, menyatakan'

In [82]:
def predict_weighted(query, k=5):

    top_cases = retrieve(query, k=k)

    scores = {}

    for _, row in top_cases.iterrows():

        cid = row["case_id"]
        sim = row["similarity"]

        sol = case_solutions[cid]

        scores[sol] = scores.get(sol, 0) + sim

    return max(scores, key=scores.get)

In [83]:
predict_weighted(
    "pengujian undang undang kehutanan"
)

'amar putusan mengadili, menyatakan'

In [84]:
queries = [
    "pengujian undang undang kehutanan",
    "perselisihan hasil pemilu presiden",
    "larangan pemakaian tanah tanpa izin"
]

In [85]:
results = []

for q in queries:

    pred = predict_weighted(q)

    top5 = retrieve(q, k=5)

    results.append({
        "query": q,
        "predicted_solution": pred,
        "top_5_case_ids": ",".join(top5["case_id"])
    })

pd.DataFrame(results)

,query,predicted_solution,top_5_case_ids
0,pengujian undang undang kehutanan,"amar putusan mengadili, menyatakan","case_013,case_016,case_006,case_012,case_014"
1,perselisihan hasil pemilu presiden,amar putusan mk 90/2023 [vide bukti p-8] berbu...,"case_010,case_024,case_001,case_025,case_009"
2,larangan pemakaian tanah tanpa izin,amar putusan sebagai berikut: 1) menyatakan,"case_003,case_016,case_013,case_012,case_011"

In [86]:
output_path = "../data/results/predictions.csv"

import os
os.makedirs("../data/results", exist_ok=True)

pd.DataFrame(results).to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:", output_path)

Saved: ../data/results/predictions.csv